# Header
menu:
  Home: /
  Archives: /archives
  Tools: /tools
  GitHub: https://github.com/eiichi-worker
  その他メモ（Gist）: https://gist.github.com/eiichi-worker
  AI実験場: http://ai.noraneko.work/
rss: /atom.xml

# Content
excerpt_link: 続きを読む
fancybox: true

# Sidebar
sidebar: right
widgets:
- category
- tag
- tagcloud
- archive
- recent_posts

# display widgets at the bottom of index pages (pagination == 2)
index_widgets:
# - category
# - tagcloud
# - archive

# widget behavior
archive_type: 'monthly'
show_count: false

# Miscellaneous
google_analytics: UA-99294159-1
favicon: /favicon.ico
twitter:
google_plus:
fb_admins:
fb_app_id:
